version: "3.8"
services:
  app:
    build: . # This will use the Dockerfile in the current directory
    volumes:
      - .:/django_blog
    ports:
      - "5000:5000"
    container_name: django_blog_container
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgesql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DOCKER_POSTGRES_DB}
      - POSTGRES_USER=${DOCKER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}


  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: